# config/config.yaml
agents:
  capture:
    role: "Thought Capture Specialist"
    goal: "Efficiently capture raw thoughts with minimal friction"
    backstory: "You excel at preserving raw ideas exactly as they occur, without judgment or alteration. Your strength is in creating a frictionless capture process."
    verbose: true
    prompt_template: "You are acting as the Capture agent. Please acknowledge that you have received and read the following text: '{thought_content}'. What is the state of washington's capital? Your response should state all actions you have taken."

  contextualize:
    role: "Context Analyst"
    goal: "Add essential metadata to raw thoughts without altering their content"
    backstory: "You have a talent for quickly identifying the domain, urgency, and relationships of thoughts without changing their original form."
    verbose: true
    prompt_template: "You are acting as the Contextualize agent. Please acknowledge that you have received and read the following text: '{thought_content}'. Your response should simply state that you've read it as the Contextualize agent."

  clarify:
    role: "Thought Clarifier"
    goal: "Expand and develop raw thoughts into more complete forms"
    backstory: "You excel at making thoughts more coherent while preserving their essence, expanding abbreviations and identifying core concepts."
    verbose: true
    prompt_template: "You are acting as the Clarify agent. Please acknowledge that you have received and read the following text: '{thought_content}'. Your response should simply state that you've read it as the Clarify agent."

  categorize:
    role: "Pattern Recognition Specialist"
    goal: "Connect thoughts to existing knowledge frameworks and identify patterns"
    backstory: "You have an exceptional ability to see how new ideas fit into existing knowledge structures and can identify emerging themes."
    verbose: true
    prompt_template: "You are acting as the Categorize agent. Please acknowledge that you have received and read the following text: '{thought_content}'. Your response should simply state that you've read it as the Categorize agent."

  crystallize:
    role: "Thought Crystallizer"
    goal: "Transform processed thoughts into their most useful and actionable forms"
    backstory: "You are skilled at distilling ideas to their essential components and structuring them optimally for their intended application."
    verbose: true
    prompt_template: "You are acting as the Crystallize agent. Please acknowledge that you have received and read the following text: '{thought_content}'. Your response should simply state that you've read it as the Crystallize agent."

  connect:
    role: "Knowledge Integrator"
    goal: "Integrate processed thoughts into broader knowledge systems"
    backstory: "You excel at establishing meaningful connections between ideas and ensuring they influence broader work and thinking."
    verbose: true
    prompt_template: "You are acting as the Connect agent. Please acknowledge that you have received and read the following text: '{thought_content}'. Your response should simply state that you've read it as the Connect agent."

tasks:
  capture:
    description: "Capture the raw thought without alteration. Focus on preserving the original idea exactly as it was conceived."
    agent: "capture"
    dependencies: []

  contextualize:
    description: "Add minimal metadata to the captured thought: category/domain tag, urgency/importance, and relation to previous thoughts."
    agent: "contextualize"
    dependencies: ["capture"]

  clarify:
    description: "Process the thought by expanding abbreviations, identifying core concepts vs. details, and flagging ambiguities."
    agent: "clarify"
    dependencies: ["contextualize"]

  categorize:
    description: "Match the thought to existing patterns/projects, identify if it's new territory or extends existing ideas, and connect to knowledge frameworks."
    agent: "categorize"
    dependencies: ["clarify"]

  crystallize:
    description: "Transform the thought into an actionable format, strip unnecessary context while preserving essence, and structure for intended use."
    agent: "crystallize"
    dependencies: ["categorize"]

  connect:
    description: "Link the thought to existing knowledge, identify implications for related projects, and generate potential next steps."
    agent: "connect"
    dependencies: ["crystallize"]

llm:
  default:
    provider: "ollama"
    model_name: "qwen2.5:14b"
    temperature: 0.7
  
  # Optional alternative configurations for specific tasks
  large_context:
    provider: "gemini"
    model_name: "gemini-1.5-pro"
    temperature: 0.5
    api_key: "AIzaSyDbVmhXnuxhucA-ORbLiTCTo4mzqFlK0h4"  # Replace with your actual API key or use env variables
  
  
  
  


folders:
  base: "/Volumes/Samsung/users/brad/Library/Mobile Documents/iCloud~md~obsidian/Documents/Digital Alchemy/"
  capture: "_inbox"
  contextualize: "2-Contextualize"
  clarify: "3-Clarify"
  categorize: "4-Categorize"
  crystallize: "5-Crystallize"
  connect: "6-Connect"