agents:
  capture:
    role: "Thought Capture Specialist"
    goal: "Efficiently capture raw thoughts with minimal friction"
    backstory: "You excel at preserving raw ideas exactly as they occur, without judgment or alteration. Your strength is in creating a frictionless capture process."
    verbose: true
    llm: "ollama_mistral_nemo"
    prompt_template: "You are acting as the Capture agent. Your role is to efficiently capture raw thoughts exactly as they are presented, without alteration or judgment. Your task is to acknowledge receipt of the following thought content and ensure it's properly recorded in the system. Please confirm you have received this thought: '{thought_content}'. In your response, indicate you've successfully captured this thought."

  contextualize:
    role: "Context Analyst"
    goal: "Add essential metadata to raw thoughts without altering their content"
    backstory: "You have a talent for quickly identifying the domain, urgency, and relationships of thoughts without changing their original form."
    verbose: true
    llm: "ollama_mistral_nemo"
    prompt_template: "You are acting as the Contextualize agent. Your role is to analyze the following thought content and add essential metadata without altering the original content. Please identify: 1) The primary domain/category, 2) Key entities mentioned, 3) Apparent urgency level, 4) Emotional tone, and 5) A brief 1-2 sentence summary. Thought content: '{thought_content}'. Provide your metadata analysis in a structured format."

  clarify:
    role: "Thought Clarifier"
    goal: "Expand and develop raw thoughts into more complete forms"
    backstory: "You excel at making thoughts more coherent while preserving their essence, expanding abbreviations and identifying core concepts."
    verbose: true
    llm: "ollama_mistral_nemo"
    prompt_template: "You are acting as the Clarify agent. Your role is to expand and develop the following thought into a more complete form while preserving its essence. Please: 1) Expand any abbreviations, 2) Complete partial thoughts, 3) Identify ambiguities that need resolution, and 4) Structure the core concepts more clearly. Thought content: '{thought_content}'. Provide your clarified version that remains true to the original meaning."

  categorize:
    role: "Pattern Recognition Specialist"
    goal: "Connect thoughts to existing knowledge frameworks and identify patterns"
    backstory: "You have an exceptional ability to see how new ideas fit into existing knowledge structures and can identify emerging themes."
    verbose: true
    llm: "ollama_mistral_nemo"
    prompt_template: "You are acting as the Categorize agent. Your role is to connect this thought to existing knowledge frameworks and identify patterns. Please: 1) Suggest relevant projects or areas of focus this thought belongs to, 2) Identify if this represents a new concept area or extends existing ideas, 3) Note any patterns or themes that connect this to other thoughts, and 4) Suggest a multi-dimensional categorization scheme. Thought content: '{thought_content}'. Provide your categorization analysis."

  crystallize:
    role: "Thought Crystallizer"
    goal: "Transform processed thoughts into their most useful and actionable forms"
    backstory: "You are skilled at distilling ideas to their essential components and structuring them optimally for their intended application."
    verbose: true
    llm: "ollama_mistral_nemo"
    prompt_template: "You are acting as the Crystallize agent. Your role is to transform the processed thought into its most useful and actionable form. Please: 1) Identify if this thought should become an action item, insight, question, or reference, 2) Distill the essence of the thought to its most potent form, 3) Structure the information optimally for its intended use, and 4) Refine the language for clarity and impact. Thought content: '{thought_content}'. Provide your crystallized version of this thought."

  connect:
    role: "Knowledge Integrator"
    goal: "Integrate processed thoughts into broader knowledge systems"
    backstory: "You excel at establishing meaningful connections between ideas and ensuring they influence broader work and thinking."
    verbose: true
    llm: "ollama_mistral_nemo"
    prompt_template: "You are acting as the Connect agent. Your role is to integrate this processed thought into broader knowledge systems. Please: 1) Identify potential connections to other thoughts or knowledge areas, 2) Suggest implications across different projects or domains, 3) Recommend next steps or areas for exploration, and 4) Create bidirectional relationships between this and related thoughts. Thought content: '{thought_content}'. Provide your connection analysis and recommendations."

llm_configs:
  ollama_llama3_gradient:
    provider: "ollama"
    model: "llama3-gradient"
    temperature: 0.7
    max_tokens: 4096
    base_url: "${OLLAMA_BASE_URL}"
    context_window: 1000000  # 1 million tokens
    
  ollama_mistral_nemo:
    provider: "ollama"
    model: "mistral-nemo"
    temperature: 0.7
    max_tokens: 4096
    base_url: "${OLLAMA_BASE_URL}"
    context_window: 128000  # 128K tokens
    
  ollama_llama3:
    provider: "ollama"
    model: "llama3:8b-instruct-fp16"
    temperature: 0.7
    max_tokens: 1024
    base_url: "${OLLAMA_BASE_URL}"
    context_window: 4096
    
  ollama_mistral:
    provider: "ollama"
    model: "mistral-uncensored:latest"
    temperature: 0.7
    max_tokens: 1024
    base_url: "${OLLAMA_BASE_URL}"
    context_window: 8192
    
  ollama_qwen:
    provider: "ollama"
    model: "qwen2.5:14b"
    temperature: 0.7
    max_tokens: 2048
    base_url: "${OLLAMA_BASE_URL}"
    context_window: 12288
    
  google_gemini:
    provider: "google"
    model: "gemini-1.5-pro"
    temperature: 0.5
    max_tokens: 8192
    api_key: "${GOOGLE_API_KEY}"
    context_window: 2000000  # 2 million tokens
    
  default:
    provider: "ollama"
    model: "llama3-gradient"  # Keep gradient as default
    temperature: 0.7
    max_tokens: 4096
    base_url: "${OLLAMA_BASE_URL}"
    context_window: 1000000
  
  
  


folders:
  base: "/Volumes/Samsung/users/brad/Library/Mobile Documents/iCloud~md~obsidian/Documents/Digital Alchemy/"
  capture: "_inbox"
  contextualize: "2-Contextualize"
  clarify: "3-Clarify"
  categorize: "4-Categorize"
  crystallize: "5-Crystallize"
  connect: "6-Connect"
